import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import {
  buildDemoReport,
  DEMO_VARIANTS,
} from "../generate-demo-reports.mjs";

const repositoryRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
);

async function checkedInReport(name) {
  const reportPath = path.join(
    repositoryRoot,
    "demo",
    "fixtures",
    `${name}.validation-report.json`,
  );
  return JSON.parse(await readFile(reportPath, "utf8"));
}

test("checked-in demo reports are generated by the current validator", async () => {
  for (const variant of DEMO_VARIANTS) {
    assert.deepEqual(await checkedInReport(variant.name), await buildDemoReport(variant));
  }
});

test("demo variants isolate the B3 route-corner decision", async () => {
  const fail = await buildDemoReport(DEMO_VARIANTS.find(({ name }) => name === "fail"));
  const pass = await buildDemoReport(DEMO_VARIANTS.find(({ name }) => name === "pass"));
  const failedChecks = fail.checks.filter(({ status }) => status === "fail");
  const failRoute = fail.checks.find(({ checkId }) => checkId === "routeWidth");

  assert.deepEqual(pass.summary, {
    overallStatus: "pass",
    total: 6,
    passed: 6,
    failedErrors: 0,
    failedWarnings: 0,
  });
  assert.deepEqual(fail.summary, {
    overallStatus: "fail",
    total: 6,
    passed: 5,
    failedErrors: 1,
    failedWarnings: 0,
  });
  assert.deepEqual(failedChecks.map(({ checkId }) => checkId), ["routeWidth"]);
  assert.ok(failRoute.measured.minimumClearWidthM >= failRoute.required.minimumClearWidthM);
  assert.ok(failRoute.measured.minimumCornerClearanceM < 0.6);
  assert.ok(Math.abs(failRoute.measured.minimumCornerClearanceM * 2 - 1.0512640011) < 1e-9);
  assert.deepEqual(failRoute.measured.conflictingObjectIds, ["table-b3"]);
});
